name: Style Check - Post Results

# This workflow uses workflow_run to safely post style check results
# from pull requests, including those from forks. It runs in the repository
# context with full permissions but does NOT execute any code from the PR -
# only reads the artifact produced by the style-check workflow.
#
# workflow_run is the recommended approach for posting results from fork PRs
# as it runs after the analysis workflow completes and has access to artifacts.
on:
  workflow_run:
    workflows: ["Style Check"]
    types:
      - completed

# Required permissions to post comments on PRs
# workflow_run runs with the repository's GITHUB_TOKEN
# which has these permissions even for PRs from forks
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  post-style-results:
    name: Post style check results to PR
    runs-on: ubuntu-latest
    # Only run if the Style Check workflow was triggered by a pull_request event
    if: github.event.workflow_run.event == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Download style check results
      uses: actions/download-artifact@v6
      with:
        name: style-results
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
      continue-on-error: true
      
    - name: Check if results exist
      id: check-results
      run: |
        if [ -f "pr-number.txt" ] && [ -f "token-check.log" ]; then
          echo "results-exist=true" >> $GITHUB_OUTPUT
          echo "✓ Style check results found"
        else
          echo "results-exist=false" >> $GITHUB_OUTPUT
          echo "ℹ Style check results not found or no warnings detected"
        fi
      
    - name: Post comment to PR
      if: steps.check-results.outputs.results-exist == 'true'
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          // Read the PR number and log file
          const prNumber = parseInt(fs.readFileSync('pr-number.txt', 'utf8').trim());
          const log = fs.readFileSync('token-check.log', 'utf8');
          
          // Construct the comment body
          const body = `## 🎨 Style Check Results
          
          The token replacement checker found some hardcoded values that could be migrated to MD3 theme variables.
          
          <details>
          <summary>View findings</summary>
          
          \`\`\`
          ${log}
          \`\`\`
          
          </details>
          
          **Note:** This is informational only. Consider migrating to theme variables for consistency.
          
          See [STYLE-MD3-EXPRESSIVE.md](../docs/STYLE-MD3-EXPRESSIVE.md) for the migration guide.
          `;
          
          // Post the comment
          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
          
          console.log(`✓ Comment posted to PR #${prNumber}`);
